#!/usr/bin/env node
/*
 * EduPulse — Sinh service-worker.js cho offline-first PWA.
 *
 * Chạy SAU `flutter build web --release` để:
 *   - Precache toàn bộ asset tĩnh của build hiện tại (offline ngay lần đầu),
 *   - Tự bump version cache theo nội dung build (tránh kẹt shell cũ khi redeploy).
 *
 * Cách chạy:  node tool/generate_sw.cjs   (từ thư mục gốc repo)
 */
'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const BUILD_DIR = path.join(__dirname, '..', 'build', 'web');
const OUT_FILE = path.join(BUILD_DIR, 'service-worker.js');

// Những file KHÔNG precache (nội dung thay đổi theo phiên / không cần thiết).
const EXCLUDE_PATTERNS = [
  /^service-worker\.js$/, // chính file SW
  /^flutter_service_worker\.js$/, // SW cũ của Flutter (tự unregister)
  /^version\.json$/, // thay đổi mỗi build, không precache
  /^\.last_build_id$/, // metadata
  /^flutter_bootstrap\.js$/, // nhỏ, chỉ nạp shell — giữ ngoài precache để linh hoạt
];

function isExcluded(rel) {
  return EXCLUDE_PATTERNS.some((re) => re.test(rel));
}

function listFiles(dir, base) {
  const out = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const e of entries) {
    const full = path.join(dir, e.name);
    const rel = path.join(base, e.name).replace(/\\/g, '/');
    if (e.isDirectory()) {
      out.push(...listFiles(full, rel));
    } else if (!isExcluded(rel)) {
      out.push(rel);
    }
  }
  return out;
}

function main() {
  if (!fs.existsSync(path.join(BUILD_DIR, 'main.dart.js'))) {
    console.error(
      'generate_sw: build/web/main.dart.js không tồn tại. Chạy `flutter build web --release` trước.'
    );
    process.exit(1);
  }

  const files = listFiles(BUILD_DIR, '').sort();
  const precache = ['./'].concat(files).filter((f) => f);

  // Version = hash của toàn bộ file build (bất kỳ thay đổi asset nào đều bump cache).
  const hasher = crypto.createHash('sha256');
  for (const rel of files) {
    try {
      hasher.update(fs.readFileSync(path.join(BUILD_DIR, rel)));
    } catch (_) {
      // bỏ qua file không đọc được
    }
  }
  const version = hasher.digest('hex').slice(0, 12);
  const CACHE = `edupulse-cache-v2-${version}`;

  const precacheJson = JSON.stringify(precache);

  const sw = `// EduPulse — Offline-First Service Worker (GENERATED by tool/generate_sw.cjs)
// Do not edit by hand — it is regenerated on every deploy.

const CACHE = ${JSON.stringify(CACHE)};

const PRECACHE = ${precacheJson};

// Install: precache toàn bộ asset build để offline ngay từ lần đầu mở.
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE))
  );
  self.skipWaiting();
});

// Activate: dọn cache phiên bản cũ + claim client ngay.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key !== CACHE)
          .map((key) => caches.delete(key))
      )
    ).then(() => self.clients.claim())
  );
});

// Fetch: cache-first cho static, network-first cho navigation (fallback index.html).
self.addEventListener('fetch', (event) => {
  const request = event.request;

  // Chỉ xử lý GET cùng-origin; POST/API/AI/Supabase đi thẳng network.
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigation: network-first, fallback về cached index.html khi offline.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          if (response && response.ok) {
            const clone = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request.url, clone));
            return response;
          }
          throw new Error('Network failed');
        })
        .catch(() =>
          caches.match('./index.html').then((r) => r || caches.match('./'))
        )
    );
    return;
  }

  // Static: cache-first (asset đã precache), fallback network + update.
  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        if (response && response.ok) {
          const clone = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, clone));
          return response;
        }
        return response;
      });
    })
  );
});
`;

  fs.writeFileSync(OUT_FILE, sw, 'utf8');
  console.log(
    `generate_sw: OK — ${precache.length} assets precache, cache="${CACHE}"`
  );
}

main();
